# Generated by Django 6.0.6 on 2026-07-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_savedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
