# Generated by Django 6.0.6 on 2026-07-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_order_cancellation_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancellation_reason',
        ),
    ]
