# Generated by Django 6.0.6 on 2026-07-23 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_order_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be digits only (10 to 15 digits).', regex='^\\d{10,15}$')]),
        ),
    ]
