# Generated by Django 6.0.6 on 2026-07-11 14:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_bill_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
